# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "upskilldevopsios lates"
  lane :tests do
    run_tests(project: "upskilldevopsios.xcodeproj",
              devices: ["iPhone 13 Pro"],
              scheme: "upskilldevopsios")
  end

  lane :distribute do
        build_ios_app(
          workspace: "upskilldevopsios.xcodeproj",
          configuration: "Release",
          scheme: "upskilldevopsios",
          silent: true,
          clean: true,
          output_directory: "path/to/dir", # Destination directory. Defaults to current directory.
          output_name: "my-app.ipa",       # specify the name of the .ipa file to generate (including file extension)
          sdk: "iOS 15.0"
        )

        firebase_app_distribution(
            app: "1:314361995162:ios:fb33010d38926da017e423",
            testers: "angel.antonov213@gmail.com",
            release_notes: "Let's test that!"
        )

    end
end
