# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "upskilldevopsios lates"
  lane :tests do
    run_tests(project: "upskilldevopsios.xcodeproj",
              devices: ["iPhone 13 Pro"],
              scheme: "upskilldevopsios")
  end
  lane :distribute do
        build_ios_app(...)
        # build_ios_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:314361995162:ios:fb33010d38926da017e423",
            testers: "angel.antonov213@gmail.com",
            release_notes: "Let's test that!"
        )

    end
end
