name: distribution_test
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  distribute_test:
    if: github.event.pull_request.merged == true
    name: Distribute
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Distributee to Firebase
      run: bundle exec fastlane distribute
