name: pr
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests
